// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzDDVjGVvnbvT3VEHOBjBeRA03uw6QgnY',
    appId: '1:36149105344:web:f761203e5b915d8a8b1325',
    messagingSenderId: '36149105344',
    projectId: 'pizza-app-6d075',
    authDomain: 'pizza-app-6d075.firebaseapp.com',
    storageBucket: 'pizza-app-6d075.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb8WzfRfZ1z6Y6A8Tz0b63weKju48_qrk',
    appId: '1:36149105344:android:723a391ecccb20658b1325',
    messagingSenderId: '36149105344',
    projectId: 'pizza-app-6d075',
    storageBucket: 'pizza-app-6d075.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYCQO3M1kShv5PIj85rmP9lEKLkVxmRBQ',
    appId: '1:36149105344:ios:e4023f4c15cf84838b1325',
    messagingSenderId: '36149105344',
    projectId: 'pizza-app-6d075',
    storageBucket: 'pizza-app-6d075.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYCQO3M1kShv5PIj85rmP9lEKLkVxmRBQ',
    appId: '1:36149105344:ios:e4023f4c15cf84838b1325',
    messagingSenderId: '36149105344',
    projectId: 'pizza-app-6d075',
    storageBucket: 'pizza-app-6d075.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzDDVjGVvnbvT3VEHOBjBeRA03uw6QgnY',
    appId: '1:36149105344:web:5baf4d34711e9edb8b1325',
    messagingSenderId: '36149105344',
    projectId: 'pizza-app-6d075',
    authDomain: 'pizza-app-6d075.firebaseapp.com',
    storageBucket: 'pizza-app-6d075.firebasestorage.app',
  );
}
